[tool.poetry]
name = "remarks"
version = "0.1.0"
description = "Extract your marks (highlights, scribbles, annotations) and convert them to markdown, pdf, png, and svg. Works with PDFs annotated on reMarkable™ paper tablets."
authors = ["Lucas Amaro <lucasrla@users.noreply.github.com>"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://github.com/lucasrla/remarks"
keywords = ["remarkable-tablet", "remarkable", "markdown", "png", "pdf", "svg", "annotations", "highlights", "scribbles"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
    "Topic :: Utilities"
]

# https://python-poetry.org/docs/dependency-specification/
[tool.poetry.dependencies]
python = "^3.8"
Shapely = "1.7.1"
PyMuPDF = "1.18.4"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
